### PR TITLE
feat: generic plugin

### PR DESCRIPTION
**Pull request by niermann999**
The cmath frontend cannot be used generically with every linear algebra library, since the subscript operator is not always available. In the current matrix algorithm implementation, a more generic solution is being used by applying the element getter instead. In this PR, this was generalized into a *generic* implementation, which can be used on top of every linear algebra plugin. The cmath, which relies on the c-style access to arrays, implementation is kept as well, since it is still shared between the ```array``` and ```vecmem``` plugins.

### CODE REVIEW

**Comment by niermann999** [comment]
Based on #130

**Comment by stephenswat** [comment]
Is this ready for review? And if so - any guidelines on how to do this? In other words, are there any major changes here or is it mostly renaming stuff?

**Comment by niermann999** [comment]
> Is this ready for review? And if so - any guidelines on how to do this? In other words, are there any major changes here or is it mostly renaming stuff?

Yes, I think a lot of it is renaming and moving code around. The getters, for example, were moved into their own files to be able to combine them with different matrix implementations

**Review by stephenswat — APPROVED** [review]
I'm not going to look through all of this, but it looks sensible; happy to scream test this.

**Pull request merged**
