### PR TITLE
Feat add vc implementation

### PR DESCRIPTION
**Pull request by niermann999**
Add the implementation of the algebra interface using vc library. The implementation is a vertical vectorization based on the existing array plugin.

### CODE REVIEW

**Comment by asalzburger** [comment]
This was marked still WIP, please have a look

**Comment by niermann999** [comment]
This is implementation works the way it is, but needs some makeover I think before it makes sense to merge, because it has some serious performance issues still. Changeing a tiny detail in one function erases them, but results in an obviously wrong calculation.

**Comment by niermann999** [comment]
Tentative results: It seems the performance issues are systemload/hardware dependent.

**Review by asalzburger — APPROVED** [review]

**Comment by asalzburger** [comment]
Thanks, even if not yet conclusive, I think we should merge that in.

**Pull request merged**
