### PR TITLE
feat: Include vecmem for memory management

### PR DESCRIPTION
**Pull request by niermann999**
Includes vecmem for the algebra-plugins in preparation for a possible vecmem based plugin

### CODE REVIEW

**Comment by beomki-yeo** [comment]
Thanks for the work. This looks good.
Can you also look into `core/include/array/include/algebra/definitions/array.hpp` to replace `std::array` with `array_s`?

**Comment by niermann999** [comment]
Yes, I will address that next. I am thinking, the static array might get its own file or is it absolutely guaranteed that it will retain the exact behaviour of ```std::array```? The types you mean are actually more container types to the algebra types right now (e.g. for alignment)

**Comment by beomki-yeo** [comment]
As far as I know std::array and vecmem::static_array works samely at least for algebras included in this repository. I am not sure if you have look into [algebra](https://github.com/acts-project/traccc/blob/main/core/include/definitions/algebra.hpp)  of traccc, but it simply replaced `std::array` with `vecmem::static_array`

**Review by asalzburger — APPROVED** [review]
Great to see this coming in!

**Pull request merged**
